---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.9.6-eclipse-temurin-17}

inputs:
  - name: source-code
  - name: pipeline

run:
  path: pipeline/tasks/maven-build.sh
